---
- hosts: server1
  become: true
  gather_facts: False
  tasks:

  - name: Install NGINX
    apt: name=nginx state=present update_cache=yes

  - name: Delete index.html
    file: path=/var/www/html/index.html state=absent

  - name: Copy index.php to /var/www/html
    copy: src=index.php dest=/var/www/html/

  - name: Restart NGINX Service
    service: name=nginx state=restarted    
